kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    tag: replica
  template:
    metadata:
      name: replicapod
      labels:
        tag: replica
    spec:
      containers:
        - name: cont2
          image: ubuntu
          command: ["/bin/bash","-c","while true; do echo Hello Replica; sleep 5; done"]

